### ISSUE TITLE
Caldera-SAML Integration Error

### ISSUE THREAD

**Issue by ansiballZ** [mitre/saml#10]
**Describe the bug**
v5.0.0
When installing the pip modules defined in requirements, I receive the following output:
 opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/py.typed -> build/lib.linux-x86_64-cpython-39/xmlsec
      running build_ext
      error: xmlsec1 is not installed or not in path.
      [end of output]

Yet xmlsec is installed.  When installing the latest modules, I do not receive the error, however SAML doesn't seem to work and not seeing any output as to why.

v4.2.0
After installing the python modules and starting Caldera, I receive "libxml could not be loaded in" and "SAML_SVC" not defined errors

**To Reproduce**
1.  Clone the SAML repository
2. Configure settings.json for the SAML plugin
3. Start Caldera

**Expected behavior**
Caldera to redirect to Okta for login 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali] Rocky Linux
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 2.8.0] v5.0.0 and 4.2.0

**Additional context**

**Comment by ansiballZ** [comment]
@elegantmoose or @uruwhy - Could I get some assistance please?

**Comment by mkultraWasHere** [comment]
@ansiballZ Unfortunately the Caldera team does not actively maintain this repo at this time. Apologies.

Note the the README on the Caldera repo which details which plugins are actively maintained.
